# Site settings
title: Timo´s Dev Blog
description: A blog about Symfony and Web Stuff
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Timo Haasch
user_description: Hello everyone! I´m Timo, a 24 years old german PHP Software Developer. I live in the small town called Paderborn and do Web stuff since 3 years now.
user_title: Software Developer
email: timo.haasch@gmail.com
twitter_username: timow_h
github_username:  thaasch
gplus_username:  110006640396769855675

gems:
    - jekyll-admin

# Google-analytics
google-analytics:
  id: "UA-66405697-2"

exclude: ['package.json', 'src' , 'node_modules']

# Build settings
markdown: kramdown